name: .NET Reusable Workflow

on:
  workflow_call:
    inputs:
      solution-file:
        description: 'Path to the .NET solution file (.sln) in the root of the repository'
        required: true
        type: string
      dotnet-version:
        description: 'Version of .NET to use'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore ${{ inputs.solution-file }}

    - name: Build the solution
      run: dotnet build ${{ inputs.solution-file }} --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ${{ inputs.solution-file }} --no-restore --verbosity normal
